FROM node:20-alpine AS build

WORKDIR /app
COPY msch/package*.json ./
COPY msch/src ./src
COPY msch/public ./public
COPY msch/index.html ./
COPY msch/vite.config.js ./
RUN npm ci
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
